/** Official MTA subway line bullets (color + letter). */
export const SUBWAY_LINES = [
  { line: '1', color: '#EE352E', textColor: 'white' },
  { line: '2', color: '#EE352E', textColor: 'white' },
  { line: '3', color: '#EE352E', textColor: 'white' },
  { line: '4', color: '#00933C', textColor: 'white' },
  { line: '5', color: '#00933C', textColor: 'white' },
  { line: '6', color: '#00933C', textColor: 'white' },
  { line: '7', color: '#B933AD', textColor: 'white' },
  { line: 'A', color: '#0039A6', textColor: 'white' },
  { line: 'C', color: '#0039A6', textColor: 'white' },
  { line: 'E', color: '#0039A6', textColor: 'white' },
  { line: 'B', color: '#FF6319', textColor: 'white' },
  { line: 'D', color: '#FF6319', textColor: 'white' },
  { line: 'F', color: '#FF6319', textColor: 'white' },
  { line: 'M', color: '#FF6319', textColor: 'white' },
  { line: 'G', color: '#6CBE45', textColor: 'white' },
  { line: 'J', color: '#996633', textColor: 'white' },
  { line: 'Z', color: '#996633', textColor: 'white' },
  { line: 'L', color: '#A7A9AC', textColor: 'white' },
  { line: 'S', color: '#808183', textColor: 'white' },
  { line: 'Q', color: '#FCCC0A', textColor: 'black' },
  { line: 'R', color: '#FCCC0A', textColor: 'black' },
]
